background = #050007
foreground = #e49800
cursor-color = #f0f0f0
selection-background = #450045
selection-foreground = #f0f0f0
background-opacity = 0.86

palette = 0=#050007
palette = 1=#9100eb
palette = 2=#008000
palette = 3=#d0d050
palette = 4=#ffc34c
palette = 5=#00a9cb
palette = 6=#e49800
palette = 7=#e49800
palette = 8=#4a4a00
palette = 9=#b840ff
palette = 10=#00bf00
palette = 11=#f0f070
palette = 12=#4040ff
palette = 13=#bf00bf
palette = 14=#7399b4
palette = 15=#f0f0f0
